// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC4UusrOY7FLAZRy4_RYsOvdniGQNO7rQ8',
    appId: '1:603735836120:web:8d58c34ba8e778f8bf1ead',
    messagingSenderId: '603735836120',
    projectId: 'xencov-ee55b',
    authDomain: 'xencov-ee55b.firebaseapp.com',
    storageBucket: 'xencov-ee55b.appspot.com',
    measurementId: 'G-NTFHKMLX2D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDjGcdTQ9bK2n6SlkrH00PoQ_sRzTHT9Uw',
    appId: '1:603735836120:android:03f01e315af5f744bf1ead',
    messagingSenderId: '603735836120',
    projectId: 'xencov-ee55b',
    storageBucket: 'xencov-ee55b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD0WmzSXNtmIbppOpb4vpQLMu1sXhjzy_s',
    appId: '1:603735836120:ios:912aedfe8643aa2ebf1ead',
    messagingSenderId: '603735836120',
    projectId: 'xencov-ee55b',
    storageBucket: 'xencov-ee55b.appspot.com',
    iosClientId: '603735836120-8reo7u3cbeg78k8nrpljarffpbcofn80.apps.googleusercontent.com',
    iosBundleId: 'com.example.xencov',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD0WmzSXNtmIbppOpb4vpQLMu1sXhjzy_s',
    appId: '1:603735836120:ios:912aedfe8643aa2ebf1ead',
    messagingSenderId: '603735836120',
    projectId: 'xencov-ee55b',
    storageBucket: 'xencov-ee55b.appspot.com',
    iosClientId: '603735836120-8reo7u3cbeg78k8nrpljarffpbcofn80.apps.googleusercontent.com',
    iosBundleId: 'com.example.xencov',
  );
}
